sudo: required

services:
- docker

language: cpp
dist: xenial
os: linux

addons:
  apt:
    update: true
    packages:
    - binfmt-support
    - qemu-user-static

matrix:
  include:
  - name: macosx
    os: osx
    compiler: clang
    osx_image: xcode11

env:
  global:
  #encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "d5LQJfaBKL9JhcgqUmOT+0sS6OdW9opdDF1LZeD0KkaJejhVyUsuUIdFjiKPw6KFl9uE/N5L6Q3urD9OJOoKfKLymrLMC+mi8ZPMiO3pI68BIFXDBg9Bi265INDHQeQNWqkOjQ5xgnoh8BawZ8rJpCW4nwcH8xDhiieNBhLTSYaMnf5pYIcgwuwNNyIDOZgZoxGW8xa+DYO1ZCzs/VorGzYK7dzyMtzPIdinXLfoESIZXv9mMCTqlE4Wl9GIC/pWbHNqtL4lBQQeG5Fmi314QgM2oyQziO+ngWKWTuc3DBVhLuE6vzClA6yH/04/GmejTMl4eUhElM0Y+YPlZ4+bM3aOslGAYkLBtb5Yzv087a3cRW3G+hSvYTjYfhVmiUxtVm621VZDUCXRFuVOAREu7hlpdKOiP9wRvaeIBuKG4A0X08JOl8k1dXnGixyF+XeUNiOHia97AJjxAxV+A2SVcAovVRbRv0mNxY577L3+2I9jYYHqo4bbkkzeneoqJeWHxhM0WW4BZ/6JOsW5TWTNOmUW4mw0UWVpUsZklbLC0CAqXkOHlgEimXPlyTixW2Q9wwqXoYIoQ9soZzjgzfDKGSHaUdu7vj0xzITMYxfwfvDerajaUvVWtBr0y27X50eeOie+TyarajqTvolPIoPbN3Bwh9LUbbdN6xme/RUAMzY="
  # Encrypted MYCI_BINTRAY_API_KEY for publishing to bintray.
  - secure: "VmP0rHmcK90uGkq2Raq8cdTLaZx8EdAuCIr+XChioC822E8qp9wwxh91a31jJbUCm1t/c8Xy66ld3iakS1c0CUCkT1INBTO9MX7ppLVVxw904G/FC/aZ8ubHBLWjx5DUKMRyj/dDf43Ke0iukbezDUuu8BSdjfPzOzM6JA40to0B5cMrMQkWo1ELNZdhBPKlD9ViTiQzSRr0nOrJOCYuqcSjyEfhRujZgEYIF7UOHqP+fuwrymofZPEmctAWC1aDmJ2LFLic/+osVqSHNMs9U05NedVbZUTgEMnRT3GqZpOjSQzreseV/aUC3jHk9UJCLRLzQIce75PJL/raqJj4Tnp3clUIMVsXJgITAlgTme0jLjQhh0DxgdI+kORppFzkhqN0mZF4kngRqTXMsKZ2L7FEuox4K5TESjJUR0YRvVzi2iVdIJnQjuhoidv3hWLxVoO0Ofp6x788e/1AbBpVvqIQA1+DniYD6BPFgtZAMpKaNs4r2AraqKh2nm0pgYtAARg9EUiFVrhd4Dos9PgMy/kiSr/OB+9z9Y+JdqOW5Q2fY8JQ40r0uidN/E+xJaZSrxsxkY/6+Dhx32MGNIPje+6Obo4FllqF2zpN2cybouzpME8LPg1FZQjSMiSU+1UDweht9rhm9gK6oMrBvixijffdzKnYXQc/8+4C92KhBAE="
  - MYCI_GIT_USERNAME=igagis
  - PACKAGE_NAME=myci
  matrix:
  - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=buster OS=debian DOCKER_IMAGE=$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=raspbian DOCKER_IMAGE=igagis/$OS:$OS_REL PACKAGE_TYPE=deb


before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker run --name ccc -v $TRAVIS_BUILD_DIR/..:/build -w /build/$(basename $TRAVIS_BUILD_DIR) -it -d $DOCKER_IMAGE bash &&
    if [ "$PACKAGE_TYPE" == "deb" ]; then
      docker exec -t ccc apt update &&
      docker exec -t ccc apt install -y devscripts equivs &&
      src/myci-deb-prepare.sh;
    fi;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then

  fi

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec -t ccc src/myci-deb-install-build-deps.sh;
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec -t ccc dpkg-buildpackage -us -uc;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    make test &&
    make install;
  fi


deploy:
- provider: script
  skip_cleanup: true
  on:
    tags: true
    condition: $PACKAGE_TYPE = deb && -z "$TRAVIS_JOB_NAME"
  script: PATH=$PATH:$TRAVIS_BUILD_DIR/src myci-deploy-debian-bintray.sh -u igagis -r $OS -p $PACKAGE_NAME -c main -d $OS_REL $TRAVIS_BUILD_DIR/../*.deb
- provider: script
  skip_cleanup: true
  script: src/myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = macosx
