sudo: required

services:
  - docker

language: cpp
dist: xenial
os: linux

env:
  - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=amd64/$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=amd64/$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=debian DOCKER_IMAGE=amd64/$OS:$OS_REL PACKAGE_TYPE=deb

matrix:
  include:
    - os: osx
      env: BUILD_NAME=macosx
      compiler: clang
      language: cpp
      osx_image: xcode8.3
    # - os: linux
    #   env: BUILD_NAME=debian
    #   compiler: gcc
    #   language: cpp
    #   dist: trusty
    # - os: linux
    #   env: BUILD_NAME=ubuntu
    #   compiler: gcc
    #   language: cpp
    #   dist: trusty
    - os: linux
      env: BUILD_NAME=raspberry_pi
      compiler: gcc
      language: cpp
      dist: trusty

env:
  global:
  #encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "d5LQJfaBKL9JhcgqUmOT+0sS6OdW9opdDF1LZeD0KkaJejhVyUsuUIdFjiKPw6KFl9uE/N5L6Q3urD9OJOoKfKLymrLMC+mi8ZPMiO3pI68BIFXDBg9Bi265INDHQeQNWqkOjQ5xgnoh8BawZ8rJpCW4nwcH8xDhiieNBhLTSYaMnf5pYIcgwuwNNyIDOZgZoxGW8xa+DYO1ZCzs/VorGzYK7dzyMtzPIdinXLfoESIZXv9mMCTqlE4Wl9GIC/pWbHNqtL4lBQQeG5Fmi314QgM2oyQziO+ngWKWTuc3DBVhLuE6vzClA6yH/04/GmejTMl4eUhElM0Y+YPlZ4+bM3aOslGAYkLBtb5Yzv087a3cRW3G+hSvYTjYfhVmiUxtVm621VZDUCXRFuVOAREu7hlpdKOiP9wRvaeIBuKG4A0X08JOl8k1dXnGixyF+XeUNiOHia97AJjxAxV+A2SVcAovVRbRv0mNxY577L3+2I9jYYHqo4bbkkzeneoqJeWHxhM0WW4BZ/6JOsW5TWTNOmUW4mw0UWVpUsZklbLC0CAqXkOHlgEimXPlyTixW2Q9wwqXoYIoQ9soZzjgzfDKGSHaUdu7vj0xzITMYxfwfvDerajaUvVWtBr0y27X50eeOie+TyarajqTvolPIoPbN3Bwh9LUbbdN6xme/RUAMzY="
  - MYCI_GIT_USERNAME=igagis
  - USE_ANDROID_NDK_VERSION=15c
  - linuxDependencies="debhelper"


before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$BUILD_NAME" ]; then
    docker pull $DOCKER_IMAGE
  fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&

    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null;
  fi
# - if [ "$BUILD_NAME" == "debian" ]; then
#     echo "deb [arch=amd64] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
#     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
#     sudo apt-get update -qq &&
#     sudo apt-get install -qq sbuild debhelper &&
#     sudo sbuild-adduser $LOGNAME &&
#     echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
#     echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
#     sudo sbuild-createchroot --include=gnupg1,dirmngr,build-essential stretch /srv/chroot/deb-amd64 http://httpredir.debian.org/debian &&
#     echo "deb [trusted=yes] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /srv/chroot/deb-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
#     sudo chroot /srv/chroot/deb-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
#     sudo chroot /srv/chroot/deb-amd64 ln -s /usr/bin/gpg1 /usr/bin/gpg;
#   fi
# - if [ "$BUILD_NAME" == "ubuntu" ]; then
#     echo "deb [arch=amd64] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
#     sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
#     sudo apt-get update -qq &&
#     sudo apt-get install -qq sbuild debhelper &&
#     sudo sbuild-adduser $LOGNAME &&
#     echo lQHYBFfZDkYBBACyRm0LCwK/9rSzqSJyEBihVNA61meWp9MVjn3EBPp6MV1/mjZ80LPJ6ecYX6VMu861a5yQLnlA9krUxuHxjnsEYvMQiz0zHapp8Zqu0FIvcU1IWZV7Eio5Lej7QFeHFmtPlrSqT152lVUmQFW9ZCtWOOM1KnKBhoWWLf9z7LnwSwARAQABAAP/SWyYHKQ8TbPeWOCgPzpB6rBz0sfbgkE8vvQg+ErUnt8WEygAqQeMBO1BMNizzBbN3AqmQPvjFM5bo6cGB+cW4tbmWVtp8wMGVm8dobiZP3p1YLtvrweX3gYo1P4km8B7JkeJ0oyGa1k4yP5m4+o7t97EanKLFTFCbJvV/txT+YECAMLhKBMGJBqa8766tsyXbKaHQKvUDwlVCltAbeRb/V7cnIEuf/bn5DcN2O3yhN35OX5EvCeJxtCSBDh9HkQfK0cCAOowGoepffgLuuOfnpNU3GcHU9lNsLUnYJ17Oa38z1JGjggrUvQ5V6UbH0YY14vQXbrOVn+YE9Job9UCnM6DzN0B/19ZoYzH9anOf+nmTM56Rrk8itQXhN/gpI22EZ9n8koELvYrHj3iUgPJ+BOCKTP3E9brojEC048pK58GFJkr+/qjqbRgU2J1aWxkIFNpZ25lciAoU2J1aWxkIEJ1aWxkIERlcGVuZGVuY3kgQXJjaGl2ZSBLZXkpIDxidWlsZGQtdG9vbHMtZGV2ZWxAbGlzdHMuYWxpb3RoLmRlYmlhbi5vcmc+iLgEEwECACIFAlfZDkYCGy8GCwkIBwMCBhUIAgkKCwQWAgMBAh4BAheAAAoJELG4iKvjYvQgomAEAJzhmqIVxIU3+ROL0B8Q2Iv1gWRe6X17J1UQPYIGkRYcZWYUllWjmk32snT5Yv+x2TMVojD0JCCgltU0JBvydovItd+g6H+C8I/bhoq5twC9CIYGKmhDInxwCdHG8yU7AVdEopf38VsEC+3Hazh4V5sPldHMo9Lx6u5uXiil5qKi | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.sec > /dev/null &&
#     echo mI0EV9kORgEEALJGbQsLAr/2tLOpInIQGKFU0DrWZ5an0xWOfcQE+noxXX+aNnzQs8np5xhfpUy7zrVrnJAueUD2StTG4fGOewRi8xCLPTMdqmnxmq7QUi9xTUhZlXsSKjkt6PtAV4cWa0+WtKpPXnaVVSZAVb1kK1Y44zUqcoGGhZYt/3PsufBLABEBAAG0YFNidWlsZCBTaWduZXIgKFNidWlsZCBCdWlsZCBEZXBlbmRlbmN5IEFyY2hpdmUgS2V5KSA8YnVpbGRkLXRvb2xzLWRldmVsQGxpc3RzLmFsaW90aC5kZWJpYW4ub3JnPoi4BBMBAgAiBQJX2Q5GAhsvBgsJCAcDAgYVCAIJCgsEFgIDAQIeAQIXgAAKCRCxuIir42L0IKJgBACc4ZqiFcSFN/kTi9AfENiL9YFkXul9eydVED2CBpEWHGVmFJZVo5pN9rJ0+WL/sdkzFaIw9CQgoJbVNCQb8naLyLXfoOh/gvCP24aKubcAvQiGBipoQyJ8cAnRxvMlOwFXRKKX9/FbBAvtx2s4eFebD5XRzKPS8erubl4opeaiog== | base64 -d | sudo tee /var/lib/sbuild/apt-keys/sbuild-key.pub > /dev/null &&
#     sudo sbuild-createchroot --include=gnupg,dirmngr,build-essential --components=main,universe xenial /srv/chroot/ubu-amd64 http://archive.ubuntu.com/ubuntu/ &&
#     echo "deb [trusted=yes] http://dl.bintray.com/igagis/ubu unstable main" | sudo tee /srv/chroot/ubu-amd64/etc/apt/sources.list.d/igagis.list > /dev/null &&
#     sudo chroot /srv/chroot/ubu-amd64 apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61;
#   fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild;
    sudo src/myci-make-raspberry-chroot.sh /srv/chroot/rasp-armhf &&
    echo "deb http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies g++ &&
    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
  fi

script:
# - if [ "$BUILD_NAME" == "debian" ]; then
#     src/myci-deb-prepare.sh &&
#     sg sbuild -c "sbuild -n -A -d stretch-amd64-sbuild --run-lintian --debbuildopts '-us -uc'";
#   fi
# - if [ "$BUILD_NAME" == "ubuntu" ]; then
#     src/myci-deb-prepare.sh &&
#     sg sbuild -c "sbuild -n -A -d xenial-amd64-sbuild --debbuildopts '-us -uc'";
#   fi
- if [ "$BUILD_NAME" == "macosx" ]; then
    make test &&
    make install;
  fi
- if [ "$BUILD_NAME" == "raspberry_pi" ]; then
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && src/myci-deb-prepare.sh" &&
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && dpkg-buildpackage -us -uc";
  fi


# before_deploy:
#   - src/myci-apply-version.sh -v `src/myci-deb-version.sh debian/changelog` travis_bintray_*.json.in


deploy:
# - provider: bintray
#   skip_cleanup: true
#   on:
#     tags: true
#     condition: $BUILD_NAME = debian
#   file: travis_bintray_deb.json
#   user: igagis
#   key:
#     secure: "roU64Mzqk7Tis7hamJ8+lagxHsEkTXnJipoQ6gMd6lYZYF5bM1hDlrqG9oZRKFJXmv6ommof12ybC96JA/XXI8Hvu1P/vYer1emRUuNa1inDPHivt5qjeEiDCRJEki2e0nONqp0qVEz/GE7BWQse34Kxex7jW/wbsA0BgoWtszv18xpYkDE/IYPKAAYGHDf2hh28++RFbShFh28ig3g2gVghxfJB0BQeg+4RxkGyUmJI4cozYTJX/mmBw/hfswsDVSjazMW0fE7ZokwrtZ9/R0zJyRpVyGq4O5b1pfAKf3tRqYhFI+Hx4Pu0mB3TxBZ5JcqxITS/rniSI5CtD27AF1W/x9Wzx8jGQFsBP11Yr7Ws2QczT6YnuVax98/tKSJU/L2d29cRWmDJrTaOOg+DOe+PCGSUzhBGageQA/FjTl66myonh6zxLZb29F0sy0fNv2tnDMFS05HbMk/dlzB+aW0U91GlicZqx+xwlxKFTmetgUsasUCLt5n0+yEji6Ay64t52cET3D5+VFDoF2WF6saqKAuAdnfBEXQEJjRWHPz3kECvx4E49s0T7HBVSrkIdebhToVOm8baj00a76+P1d3GKZO8BCYB1AnNcY/74dPllaIz1lL05qzOPrzytfc6GcedSBMlDD/u7Ow82sE7wkl1S7Fh5xKkesILWuKuvSo="
#   dry-run: false
# - provider: bintray
#   skip_cleanup: true
#   on:
#     tags: true
#     condition: $BUILD_NAME = ubuntu
#   file: travis_bintray_ubu.json
#   user: igagis
#   key:
#     secure: "roU64Mzqk7Tis7hamJ8+lagxHsEkTXnJipoQ6gMd6lYZYF5bM1hDlrqG9oZRKFJXmv6ommof12ybC96JA/XXI8Hvu1P/vYer1emRUuNa1inDPHivt5qjeEiDCRJEki2e0nONqp0qVEz/GE7BWQse34Kxex7jW/wbsA0BgoWtszv18xpYkDE/IYPKAAYGHDf2hh28++RFbShFh28ig3g2gVghxfJB0BQeg+4RxkGyUmJI4cozYTJX/mmBw/hfswsDVSjazMW0fE7ZokwrtZ9/R0zJyRpVyGq4O5b1pfAKf3tRqYhFI+Hx4Pu0mB3TxBZ5JcqxITS/rniSI5CtD27AF1W/x9Wzx8jGQFsBP11Yr7Ws2QczT6YnuVax98/tKSJU/L2d29cRWmDJrTaOOg+DOe+PCGSUzhBGageQA/FjTl66myonh6zxLZb29F0sy0fNv2tnDMFS05HbMk/dlzB+aW0U91GlicZqx+xwlxKFTmetgUsasUCLt5n0+yEji6Ay64t52cET3D5+VFDoF2WF6saqKAuAdnfBEXQEJjRWHPz3kECvx4E49s0T7HBVSrkIdebhToVOm8baj00a76+P1d3GKZO8BCYB1AnNcY/74dPllaIz1lL05qzOPrzytfc6GcedSBMlDD/u7Ow82sE7wkl1S7Fh5xKkesILWuKuvSo="
#   dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $BUILD_NAME = raspberry_pi
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "roU64Mzqk7Tis7hamJ8+lagxHsEkTXnJipoQ6gMd6lYZYF5bM1hDlrqG9oZRKFJXmv6ommof12ybC96JA/XXI8Hvu1P/vYer1emRUuNa1inDPHivt5qjeEiDCRJEki2e0nONqp0qVEz/GE7BWQse34Kxex7jW/wbsA0BgoWtszv18xpYkDE/IYPKAAYGHDf2hh28++RFbShFh28ig3g2gVghxfJB0BQeg+4RxkGyUmJI4cozYTJX/mmBw/hfswsDVSjazMW0fE7ZokwrtZ9/R0zJyRpVyGq4O5b1pfAKf3tRqYhFI+Hx4Pu0mB3TxBZ5JcqxITS/rniSI5CtD27AF1W/x9Wzx8jGQFsBP11Yr7Ws2QczT6YnuVax98/tKSJU/L2d29cRWmDJrTaOOg+DOe+PCGSUzhBGageQA/FjTl66myonh6zxLZb29F0sy0fNv2tnDMFS05HbMk/dlzB+aW0U91GlicZqx+xwlxKFTmetgUsasUCLt5n0+yEji6Ay64t52cET3D5+VFDoF2WF6saqKAuAdnfBEXQEJjRWHPz3kECvx4E49s0T7HBVSrkIdebhToVOm8baj00a76+P1d3GKZO8BCYB1AnNcY/74dPllaIz1lL05qzOPrzytfc6GcedSBMlDD/u7Ow82sE7wkl1S7Fh5xKkesILWuKuvSo="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: src/myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $BUILD_NAME = macosx
