sudo: required

services:
- docker

language: cpp
dist: xenial
os: linux

matrix:
  include:
  - name: macosx
    os: osx
    compiler: clang
    osx_image: xcode8.3
  - name: raspberry_pi
    os: linux
    compiler: gcc

env:
  global:
  #encrypted MYCI_GIT_ACCESS_TOKEN for publishing to homebrew-tap
  - secure: "d5LQJfaBKL9JhcgqUmOT+0sS6OdW9opdDF1LZeD0KkaJejhVyUsuUIdFjiKPw6KFl9uE/N5L6Q3urD9OJOoKfKLymrLMC+mi8ZPMiO3pI68BIFXDBg9Bi265INDHQeQNWqkOjQ5xgnoh8BawZ8rJpCW4nwcH8xDhiieNBhLTSYaMnf5pYIcgwuwNNyIDOZgZoxGW8xa+DYO1ZCzs/VorGzYK7dzyMtzPIdinXLfoESIZXv9mMCTqlE4Wl9GIC/pWbHNqtL4lBQQeG5Fmi314QgM2oyQziO+ngWKWTuc3DBVhLuE6vzClA6yH/04/GmejTMl4eUhElM0Y+YPlZ4+bM3aOslGAYkLBtb5Yzv087a3cRW3G+hSvYTjYfhVmiUxtVm621VZDUCXRFuVOAREu7hlpdKOiP9wRvaeIBuKG4A0X08JOl8k1dXnGixyF+XeUNiOHia97AJjxAxV+A2SVcAovVRbRv0mNxY577L3+2I9jYYHqo4bbkkzeneoqJeWHxhM0WW4BZ/6JOsW5TWTNOmUW4mw0UWVpUsZklbLC0CAqXkOHlgEimXPlyTixW2Q9wwqXoYIoQ9soZzjgzfDKGSHaUdu7vj0xzITMYxfwfvDerajaUvVWtBr0y27X50eeOie+TyarajqTvolPIoPbN3Bwh9LUbbdN6xme/RUAMzY="
  - MYCI_GIT_USERNAME=igagis
  - USE_ANDROID_NDK_VERSION=15c
  - linuxDependencies="debhelper"
  matrix:
  - OS_REL=xenial OS=ubuntu DOCKER_IMAGE=amd64/$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=bionic OS=ubuntu DOCKER_IMAGE=amd64/$OS:$OS_REL PACKAGE_TYPE=deb
  - OS_REL=stretch OS=debian DOCKER_IMAGE=amd64/$OS:$OS_REL PACKAGE_TYPE=deb


before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker run --name ccc -v $(pwd):/build -it -d $DOCKER_IMAGE bash &&
    docker exec ccc apt update &&
    docker exec ccc apt install -y devscripts equivs &&
    if [ "PACKAGE_TYPE" == "deb" ]; then src/myci-deb-prepare.sh; fi;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    rvm install ruby-2.3.3 &&
    rvm use ruby-2.3.3 &&

    brew update > /dev/null &&
    brew tap igagis/tap &&
    brew update > /dev/null;
  fi
- if [ "$TRAVIS_JOB_NAME" == "raspberry_pi" ]; then
    echo "deb [arch=amd64] http://dl.bintray.com/igagis/deb unstable main" | sudo tee /etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 379CE192D401AB61 &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq sbuild;
    sudo src/myci-make-raspberry-chroot.sh /srv/chroot/rasp-armhf &&
    echo "deb http://dl.bintray.com/igagis/rasp unstable main" | sudo tee /srv/chroot/rasp-armhf/etc/apt/sources.list.d/igagis.list > /dev/null &&
    sudo chroot /srv/chroot/rasp-armhf apt-get update &&
    sudo chroot /srv/chroot/rasp-armhf apt-get install --allow-unauthenticated -qq -y $linuxDependencies g++ &&
    sudo mkdir -p /srv/chroot/rasp-armhf/build &&
    sudo rsync -av $TRAVIS_BUILD_DIR/ /srv/chroot/rasp-armhf/build/;
  fi

install:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc bash -c "cd /build && mk-build-deps --install debian/control";
  fi

script:
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ -z "$TRAVIS_JOB_NAME" ]; then
    docker exec ccc dpkg-buildpackage;
  fi
- if [ "$TRAVIS_JOB_NAME" == "macosx" ]; then
    make test &&
    make install;
  fi
- if [ "$TRAVIS_JOB_NAME" == "raspberry_pi" ]; then
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && src/myci-deb-prepare.sh" &&
    sudo chroot /srv/chroot/rasp-armhf bash -c "cd /build && dpkg-buildpackage -us -uc";
  fi


# before_deploy:
#   - src/myci-apply-version.sh -v `src/myci-deb-version.sh debian/changelog` travis_bintray_*.json.in


deploy:
# - provider: bintray
#   skip_cleanup: true
#   on:
#     tags: true
#     condition: $TRAVIS_JOB_NAME = debian
#   file: travis_bintray_deb.json
#   user: igagis
#   key:
#     secure: "roU64Mzqk7Tis7hamJ8+lagxHsEkTXnJipoQ6gMd6lYZYF5bM1hDlrqG9oZRKFJXmv6ommof12ybC96JA/XXI8Hvu1P/vYer1emRUuNa1inDPHivt5qjeEiDCRJEki2e0nONqp0qVEz/GE7BWQse34Kxex7jW/wbsA0BgoWtszv18xpYkDE/IYPKAAYGHDf2hh28++RFbShFh28ig3g2gVghxfJB0BQeg+4RxkGyUmJI4cozYTJX/mmBw/hfswsDVSjazMW0fE7ZokwrtZ9/R0zJyRpVyGq4O5b1pfAKf3tRqYhFI+Hx4Pu0mB3TxBZ5JcqxITS/rniSI5CtD27AF1W/x9Wzx8jGQFsBP11Yr7Ws2QczT6YnuVax98/tKSJU/L2d29cRWmDJrTaOOg+DOe+PCGSUzhBGageQA/FjTl66myonh6zxLZb29F0sy0fNv2tnDMFS05HbMk/dlzB+aW0U91GlicZqx+xwlxKFTmetgUsasUCLt5n0+yEji6Ay64t52cET3D5+VFDoF2WF6saqKAuAdnfBEXQEJjRWHPz3kECvx4E49s0T7HBVSrkIdebhToVOm8baj00a76+P1d3GKZO8BCYB1AnNcY/74dPllaIz1lL05qzOPrzytfc6GcedSBMlDD/u7Ow82sE7wkl1S7Fh5xKkesILWuKuvSo="
#   dry-run: false
# - provider: bintray
#   skip_cleanup: true
#   on:
#     tags: true
#     condition: $TRAVIS_JOB_NAME = ubuntu
#   file: travis_bintray_ubu.json
#   user: igagis
#   key:
#     secure: "roU64Mzqk7Tis7hamJ8+lagxHsEkTXnJipoQ6gMd6lYZYF5bM1hDlrqG9oZRKFJXmv6ommof12ybC96JA/XXI8Hvu1P/vYer1emRUuNa1inDPHivt5qjeEiDCRJEki2e0nONqp0qVEz/GE7BWQse34Kxex7jW/wbsA0BgoWtszv18xpYkDE/IYPKAAYGHDf2hh28++RFbShFh28ig3g2gVghxfJB0BQeg+4RxkGyUmJI4cozYTJX/mmBw/hfswsDVSjazMW0fE7ZokwrtZ9/R0zJyRpVyGq4O5b1pfAKf3tRqYhFI+Hx4Pu0mB3TxBZ5JcqxITS/rniSI5CtD27AF1W/x9Wzx8jGQFsBP11Yr7Ws2QczT6YnuVax98/tKSJU/L2d29cRWmDJrTaOOg+DOe+PCGSUzhBGageQA/FjTl66myonh6zxLZb29F0sy0fNv2tnDMFS05HbMk/dlzB+aW0U91GlicZqx+xwlxKFTmetgUsasUCLt5n0+yEji6Ay64t52cET3D5+VFDoF2WF6saqKAuAdnfBEXQEJjRWHPz3kECvx4E49s0T7HBVSrkIdebhToVOm8baj00a76+P1d3GKZO8BCYB1AnNcY/74dPllaIz1lL05qzOPrzytfc6GcedSBMlDD/u7Ow82sE7wkl1S7Fh5xKkesILWuKuvSo="
#   dry-run: false
- provider: bintray
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = raspberry_pi
  file: travis_bintray_rasp.json
  user: igagis
  key:
    secure: "roU64Mzqk7Tis7hamJ8+lagxHsEkTXnJipoQ6gMd6lYZYF5bM1hDlrqG9oZRKFJXmv6ommof12ybC96JA/XXI8Hvu1P/vYer1emRUuNa1inDPHivt5qjeEiDCRJEki2e0nONqp0qVEz/GE7BWQse34Kxex7jW/wbsA0BgoWtszv18xpYkDE/IYPKAAYGHDf2hh28++RFbShFh28ig3g2gVghxfJB0BQeg+4RxkGyUmJI4cozYTJX/mmBw/hfswsDVSjazMW0fE7ZokwrtZ9/R0zJyRpVyGq4O5b1pfAKf3tRqYhFI+Hx4Pu0mB3TxBZ5JcqxITS/rniSI5CtD27AF1W/x9Wzx8jGQFsBP11Yr7Ws2QczT6YnuVax98/tKSJU/L2d29cRWmDJrTaOOg+DOe+PCGSUzhBGageQA/FjTl66myonh6zxLZb29F0sy0fNv2tnDMFS05HbMk/dlzB+aW0U91GlicZqx+xwlxKFTmetgUsasUCLt5n0+yEji6Ay64t52cET3D5+VFDoF2WF6saqKAuAdnfBEXQEJjRWHPz3kECvx4E49s0T7HBVSrkIdebhToVOm8baj00a76+P1d3GKZO8BCYB1AnNcY/74dPllaIz1lL05qzOPrzytfc6GcedSBMlDD/u7Ow82sE7wkl1S7Fh5xKkesILWuKuvSo="
  dry-run: false
- provider: script
  skip_cleanup: true
  script: src/myci-deploy-homebrew.sh -t igagis/tap
  on:
    tags: true
    condition: $TRAVIS_JOB_NAME = macosx
