branches:
  only:
    - master

os: Visual Studio 2017
version: "{branch}-{build}"

clone_folder: c:\build

environment:
  MYCI_BINTRAY_API_KEY:
    secure: t04W/09OyK0B8CxJHydCkay+Fm3i6KkBciVXjzk0u09v6F9wtDn/dsuqd5eMIj8s

install:

before_build:

build_script:
  - C:\msys64\usr\bin\bash -lc "cd /c/build/ && src/myci-apply-version.sh -v `src/myci-deb-version.sh debian/changelog` msys2/PKGBUILD.in"
  - C:\msys64\usr\bin\bash -lc "cd /c/build/msys2 && makepkg --skipinteg"

test_script:

deploy_script:
  - cmd: if "%APPVEYOR_REPO_TAG%"=="true" (C:\msys64\usr\bin\bash -lc "cd /c/build && PATH=$PATH:src src/myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw/msys -d igagis_msys msys2/*.tar.xz") else (echo Skipping deploy because not a tagged commit.)

artifacts:
  - path: msys2/*.pkg.tar.xz
