branches:
  only:
    - master

os: Visual Studio 2015
version: "{branch}-{build}"

clone_folder: c:\projects\build

environment:
  BASH: C:\msys64\usr\bin\env MSYSTEM=MINGW64 C:\msys64\usr\bin\bash
#  MYCI_GIT_USERNAME: igagis
#  MYCI_GIT_ACCESS_TOKEN:
#    secure: mpW6B2ols1a2FkshjKjryBuvBt8A1TpU9WGn+/d6PIQiZlzA0Rpo1ETKpmy0bnvX
#  DEPS: make,gcc-g++

install:

before_build:

build_script:
  - cmd: "%BASH% -lc \"cd /c/projects/build/ && src/myci-apply-version.sh -v `src/myci-deb-version.sh debian/changelog` msys2/PKGBUILD.in\""
  - cmd: "%BASH% -lc \"cd /c/projects/build/msys2 && makepkg --skipinteg && ls\""

test_script:

deploy_script:
  - cmd: if "%APPVEYOR_REPO_TAG%"=="true" (%BASH% -lc "cd /c/projects/build && src/myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw/x86_64 msys2/*.tar.xz") else (echo Skipping deploy because not a tagged commit.)
