branches:
  only:
    - master

os: Visual Studio 2015
version: "{branch}-{build}"

clone_folder: c:\projects\build

environment:
  BASH: C:\msys64\usr\bin\env MSYSTEM=MINGW64 C:\msys64\usr\bin\bash
  MYCI_GIT_USERNAME: igagis
  MYCI_GIT_ACCESS_TOKEN:
    secure: mpW6B2ols1a2FkshjKjryBuvBt8A1TpU9WGn+/d6PIQiZlzA0Rpo1ETKpmy0bnvX
  DEPS: make,gcc-g++

install:
#  - cmd: C:\cygwin64\setup-x86_64.exe -g -q -P cygport,calm,%DEPS%
#  - cmd: C:\cygwin\setup-x86.exe -g -q -P cygport,calm,%DEPS%

before_build:
#  - cmd: xcopy /S C:\projects\build C:\cygwin64\home\appveyor\
#  - cmd: xcopy /S C:\projects\build C:\cygwin\home\appveyor\
#  - cmd: xcopy /S C:\projects\build C:\msys64\home\appveyor\

build_script:
  - cmd: %BASH% -lc "(cd /c/projects/build/ && src/myci-apply-version.sh -v `src/myci-deb-version.sh debian/changelog` msys2/PKGBUILD.in)"
  - cmd: %BASH% -lc "(cd /c/projects/build/msys2 && makepkg-mingw --skipinteg && ls)"
# cyggport downloads tagged sources from github, so use cygport only for tagged commits, otherwise build with just make.
  # - cmd: if "%APPVEYOR_REPO_TAG%"=="true" (
  #           C:\cygwin64\bin\bash -e -l -c "src/myci-apply-version.sh -v `src/myci-deb-version.sh debian/changelog` cygwin/*.in" &&
  #           C:\cygwin64\bin\bash -e -l -c "cygport cygwin/*.cygport download" &&
  #           C:\cygwin64\bin\bash -e -l -c "cygport cygwin/*.cygport all" &&
  #           C:\cygwin\bin\bash -e -l -c "src/myci-apply-version.sh -v `src/myci-deb-version.sh debian/changelog` cygwin/*.in" &&
  #           C:\cygwin\bin\bash -e -l -c "cygport cygwin/*.cygport download" &&
  #           C:\cygwin\bin\bash -e -l -c "cygport cygwin/*.cygport all"
  #       ) else (
  #           C:\cygwin64\bin\bash -e -l -c "make" &&
  #           C:\cygwin\bin\bash -e -l -c "make"
  #       )

test_script:
  # - cmd: C:\cygwin64\bin\bash -e -l -c "PATH=$PATH:~/src make test"
  # - cmd: C:\cygwin\bin\bash -e -l -c "PATH=$PATH:~/src make test"
   - cmd: C:\msys64\mingw64 "PATH=$PATH:~/src make test"

deploy_script:
  # - cmd: C:\cygwin64\bin\bash -e -l -c "make install"
  # - cmd: C:\cygwin\bin\bash -e -l -c "make install"
  # - cmd: if "%APPVEYOR_REPO_TAG%"=="true" (C:\cygwin64\bin\bash -e -l -c "myci-deploy-cygwin.sh -r igagis/cygwin-repo" && C:\cygwin\bin\bash -e -l -c "myci-deploy-cygwin.sh -r igagis/cygwin-repo") else (echo Skipping deploy because not a tagged commit.)
