branches:
  only:
    - master

os: Visual Studio 2015
version: "{branch}-{build}"

clone_folder: c:\build

environment:
  BASH: C:\msys64\usr\bin\env MSYSTEM=MINGW64 C:\msys64\usr\bin\bash
  MYCI_BINTRAY_API_KEY:
    secure: t04W/09OyK0B8CxJHydCkay+Fm3i6KkBciVXjzk0u09v6F9wtDn/dsuqd5eMIj8s

install:

before_build:

build_script:
  - cmd: "%BASH% -lc \"cd /c/build/ && src/myci-apply-version.sh -v `src/myci-deb-version.sh debian/changelog` msys2/PKGBUILD.in\""
  - cmd: "%BASH% -lc \"cd /c/build/msys2 && makepkg --skipinteg\""

test_script:

deploy_script:
  - cmd: if "%APPVEYOR_REPO_TAG%"=="true" (%BASH% -lc "cd /c/build && src/myci-deploy-pacman-bintray.sh -u igagis -r msys2 -p mingw/x86_64 msys2/*.tar.xz") else (echo Skipping deploy because not a tagged commit.)
